name: Build & Release

on:
  push:
    tags:
      - '*'

jobs:
  build_for_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: install linux dependencies
        run: npm install
      - name: make and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  build_for_mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: install dependencies
        run: npm install
      - name: make and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
